application: loftidb
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /api/.*
  script: main.py

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /js
  static_dir: static/js

- url: /img
  static_dir: static/img

- url: /css
  static_dir: static/css

inbound_services:
- channel_presence